version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: rails_app_db
    volumes:
      - mysql-master-data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - rails-app-network

  redis-master:
    image: redis:7.4.0-alpine
    container_name: redis-master
    ports: # 바인딩할 포트:내부 포트
      - "6380:6379"
    volumes: # 마운트할 볼륨 설정
      - redis-master-data:/data
    networks:
      - rails-app-network

networks:
  rails-app-network:
    name: rails-app-network

volumes:
  mysql-master-data:
  redis-master-data:
