spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutorial
    username: root
    password: matsosik_password # local 환경에 있던 postgresql 계정...
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
