version: '3'
services:
  db:
    image: mysql:8.0.33
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - mysql_db_network
    ports:
      - "3311:3306"

volumes:
  mysql_db_data:

networks:
  mysql_db_network:
    name: mysql_db_network # 네트워크 이름 명시
