name: Run RSpec

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
		  MYSQL_HOST: 127.0.0.1
		  MYSQL_DB: rails_app_db_test
		  MYSQL_ROOT_PASSWORD: mysql
#MYSQL_USER: root
#		  MYSQL_PASSWORD: mysql
#         MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - "3310:3306"
    env:
	  RAILS_ENV: test
	
	steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install dependencies
      run: bundle install

    - name: Set up database
      run: |
        bin/rails db:create
		bin/rails db:migrate

    - name: Run tests
      run: bundle exec rspec

