# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master", "develop" ]
jobs:
  run-rspec:
    runs-on: ubuntu-latest

    # Test MySQL DB
    services:
      mysql:
        image: mysql:8.0
        ports:
          - "3310:3306"
        env:
          MYSQL_DB: rails_app_db_test
          # POSTGRES_USER: rails
          MYSQL_ROOT_PASSWORD: mysql
    env:
      RAILS_ENV: test
      #DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

    # Github actions permissions (PR comment에 테스트 결과 리포팅을 위해 필수)
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Set rails-app source code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      # Add or replace database setup steps here
      - name: install gem
        run: bundle install
        working-directory: ./rails-app
      - name: Set up test database
        run: |
          bin/rails db:create
          bin/rails db:migrate
        working-directory: ./rails-app
      # Add or replace test runners here
      - name: Run rspec and make rspec_result.json file
        run: |
          mkdir -p tmp
          bundle exec rspec . --format j --out tmp/rspec_result.json
        working-directory: ./rails-app

      - name: Comment fail test on Pull Request
        if: failure() # when before step was fail, do this step
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('rails-app/tmp/rspec_result.json', 'utf8'));
            
            let comment = `## RSpec Test Results\n\n`;
            
            results.examples.forEach(test => {
              if (test.status === 'failed') {
                comment += `- **${test.full_description}**: ${test.status}\n`;
                comment += `  - Message: ${test.exception.message}\n`;
                comment += `  - Backtrace: ${test.exception.backtrace.join("\n")}\n`;
              }
            });

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_ISSUE_GITHUB_TOKEN }}     

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
  #       with:
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
